### ISSUE TITLE
Batch requests URL params lost

### ISSUE THREAD

**Issue by dioncodes** [digitonic/iex-cloud-sdk#16]
For Batch requests (class \Digitonic\IexCloudSdk\Stocks\Batch) the endpoint URL is built incorrectly. The parameters (symbols, type(s)) are overwritten by the token when the request is being sent.

The classes endpoint before the request ist executed: `stock/market/batch?types=price&symbols=AAPL%2CABC`.
The request actually sent is: `https://cloud.iexapis.com/v1/stock/market/batch?token=xyz`

There is a possible workaround though, which is to move the symbols and types to the guzzle client query params:

```
$guzzle = new Client([
	'base_uri' => $iexConfig['base_url'],
	'headers' => [
		'Accept' => 'application/json',
		'Content-Type' => 'application/json'
	],
	'query' => [
		'token' => $iexConfig['secret_key'],
		'symbols' => 'AAPL,ABC',
		'types' => 'price'
	]
]);

$client = new \Digitonic\IexCloudSdk\Client($guzzle);
$req = new \Digitonic\IexCloudSdk\Stocks\Batch($client);
$req->setSymbols('ignored', 'ignored');
$req->setTypes('ignored');
$req->get();
```

**Comment by richdynamix** [comment]
This is now fixed in [0.5.1](https://github.com/digitonic/iex-cloud-sdk/releases/tag/0.5.1)
