### ISSUE TITLE
Is this still being developed?

### ISSUE THREAD

**Issue by devbanana** [digitonic/iex-cloud-sdk#9]
Is this still being developed? It seems like it's missing a lot, like the stock/{symbol}/quote endpoint for example. I tried batch but it has a bug in it where the query parameters are overridden and so the types parameter is never passed.

**Comment by richdynamix** [comment]
Sorry for the delay @devbanana . Yes the package is in heavy development. I haven't had the chance lately to continue with development but I am happy to accept PRs for features and bug fixes.

There is a status page in the documentation but I feel might be out of date given the speed IEX Cloud moves. - https://digitonic.github.io/iex-cloud-sdk/#/getting-started
